baseURL: http://leizungjyun.github.io/
languageCode: en-us
title: Shaun's Webyard

theme: PaperMod

params:
  homeInfoParams:
    title: Hi, there!
    content: Science, Technology, and Art
  socialIcons:
    - name: github
      url: https://github.com/leizungjyun
  showBreadCrumbs: true
  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"] 
menu: 
  main:
    - name: Search
      url: /search/
      weight: 5
    - name: Tags
      url: /tags/
      weight: 20
    - name: Archives
      url: /archives/
      weight: 10
    - name: About
      url: /about/
      weight: 30
       
 

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary